# Generated by Django 2.2.4 on 2019-08-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0004_pontoturistico_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='enderecos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Enderecos'),
        ),
    ]
